# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session:
        enabled: true
        handler_id: null # Ou un handler personnalisé si nécessaire
        cookie_lifetime: 3600
        save_path: '%kernel.cache_dir%/sessions'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
